branch-defaults:
  master:
    environment: null
global:
  application_name: bunny
  default_ec2_keyname: test-secret
  default_platform: Ruby 2.1 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
